# aliases
export BROWSER=firefox
alias ls="ls --color"
alias please='sudo $(fc -n -l -1)';
alias ack='ack-grep';

# general - generated by config
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt autocd notify
unsetopt beep extendedglob
bindkey -e

# set prompt and all
autoload -Uz compinit promptinit
compinit
promptinit
prompt redhat

# the BASE16 theme stuff
BASE16_SHELL="$HOME/.config/base16-shell/base16-ocean-breeze.dark.sh"
[[ -s $BASE16_SHELL ]] && source $BASE16_SHELL
