---
# top-level playbook for everything

- name: setup Arch Linux server workstation
  hosts: localhost
  become: true
  vars:
    username: "randall"
  roles:
    - arch
    - server
    - common

- name: setup Fedora Linux server workstation
  hosts: fedora
  become: true
  vars:
    username: "randall"
  roles:
    - fedora
    - server
    - common

- name: setup MacOS laptop workstation
  hosts: macos
  become: true
  vars:
    username: "randall"
  roles:
    - osx
    - common
