---
# profile for Fedora-specific setup

- name: upgrade existing Fedora packages
  dnf:
    update_cache: true
    update_only: true

- name: install Fedora packages
  dnf:
    name: "ack, elixir, git, neovim, sudo, tmux, zsh"
