# WSL needs umask
umask 22

# aliases
alias n="nvim"
alias vim="nvim"
alias please='sudo $(fc -n -l -1)'

# important exports
export TERM=xterm-256color
export EDITOR=vim

# history
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000

# options
setopt autocd               # automatically change direcotories
unsetopt beep extendedglob  # don't beep, don't extendedglob?
bindkey -v                  # vim style keybindings

# autocompletion
autoload -Uz compinit promptinit
compinit

# prompt
promptinit
PROMPT="%(!.ROOT .)%~ %% "
RPROMPT=""

# set the dircolors
d=.dircolors
test -r $d && eval "$(dircolors $d)"

# load an optional profile
test -r ~/.profile && source ~/.profile
