---
# profile for Arch-specific setup

- name: upgrade existing Pacman packages
  pacman:
    update_cache: true
    upgrade: true

- name: install select Pacman packages
  pacman:
    name: "ack elixir git neovim python-neovim sudo tmux zsh"
