#!/bin/sh

# Load the .Xresources file.
xrdb -load ~/.Xresources

# Setup Background
./.fehbg

# Start the hotkey daemon.
sxhkd &

# Start polybar!
polybar takmobar &

# Set the default cursor
xsetroot -cursor_name left_ptr

# Compositing! (maybe not right now)
compton &

# List the monitors.
bspc monitor -d one two three four five

# Window gaps/borders.
bspc config normal_border_color #000000
bspc config active_border_color #000000
bspc config focused_border_color #D8DEE9
bspc config border_width 2
bspc config window_gap 12
bspc config split_ratio 0.52

# Focus follows pointer.
bspc config focus_follows_pointer true
