---
# common setup for all profiles

- name: create dotfiles
  become_user: "{{username}}"
  copy:
    force: false
    dest: "/home/{{username}}/{{item}}"
    src: "{{item}}"
  with_items:
    - ".config/nvim/init.vim"
    - ".tmux.conf"
    - ".vimrc"
    - ".zshrc"

- name: install node version manager
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | zsh
  args:
    creates: "/home/{{username}}/.nvm/nvm.sh"
